version: '3'
services:
  frontend:
    build: frontend/.
    ports:
      - '8081:8080'
    volumes:
      - ./frontend:/usr/local/app/
      - exclude:/usr/local/app/node_modules/
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  api:
    build: . # weź z bieżącego katalogu dockerfile
    ports:
      - '5000:5000'

volumes:
  exclude: